### ISSUE TITLE
Using multiple services with a single Roman instance

### ISSUE THREAD

**Issue by DonnchaC** [wireapp/roman#4]
What is the best way to deploy multiple services using a single instance of the Roman proxy? Lithium is validating the service requests received from Wire based on the service token that it reads from the `SERVICE_TOKEN` environment variable.

In `AuthenticationFilter.java`:
```java
        String serviceToken = System.getenv("SERVICE_TOKEN");

        if (!Objects.equals(token, serviceToken)) {
            Exception cause = new IllegalArgumentException("Wrong service token");
            throw new WebApplicationException(cause, Response.Status.FORBIDDEN);
        }
```

The request only appears to be passed to the roman `MessageHandler` class if the auth check in Lithium first passes. 

Is it possible to move this auth check to Roman or else to make this extra authentication clearer in the documentation?

**Comment by dkovacevic** [comment]
You could have multiple services hitting the same instance of Roman proxy.
I just limited one service per account. You could register account A and create a service Sa.
Then you reg another account B and service Sb.
You need to provide different email addresses when registering/signing... user+1@gmail.com, user+2@gmail.com...

**Comment by dkovacevic** [comment]
I believe PR #5 might have fixed this issue too. Notice how I overrode the base class method and registered 3 new filters just for Roman service.
